{
 "title": "Resource Model Exporter2",
 "description": "To check the regression modeling of resources",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(res_model_regression_r2, container)"
    }
   },
   {
    "name": "resource",
    "query": {
     "query": "label_values(res_model_regression_r2, resource)"
    }
   },
   { "name": "interval", "query": "30s,1m,5m" }
  ]
 },
 "panels": [
  { "title": "Config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$container CPU_model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "repeat": "container",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "res_model_measurement_config{container=~\"$container\"}",
     "legendFormat": "{{cpu_model}}"
    }
   ]
  },
  {
   "title": "$container Image",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "res_model_measurement_config{container=~\"$container\"}",
     "legendFormat": "{{image_version}}"
    }
   ]
  },
  { "title": "Regression Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "R² $resource $container",
   "type": "stat",
   "description": "Quality of prediction",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max by (resource,container)(res_model_regression_r2{resource=~\"$resource\",container=~\"$container\"})[$__range:])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Variance $resource $container",
   "type": "stat",
   "description": "Range of the samples in the regression",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 11 },
   "repeat": "resource",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max by (resource,container)(res_model_regression_variance{resource=~\"$resource\",container=~\"$container\"})[$__range:])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "N $resource $container",
   "type": "stat",
   "description": "Number of samples in the regression",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "repeat": "resource",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max by (resource,container)(res_model_regression_n{resource=~\"$resource\",container=~\"$container\"})[$__range:])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "formula $resource $container",
   "type": "stat",
   "description": "Number of samples in the regression",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 17 },
   "repeat": "resource",
   "targets": [
    {
     "expr": "res_model_regression_r2{resource=~\"$resource\",container=~\"$container\"}",
     "legendFormat": "{{formula}}"
    }
   ]
  },
  { "title": "Real Usage vs Prediction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU $container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "m cores" } },
   "yaxes": [
    { "format": "m cores" }
   ],
   "targets": [
    {
     "expr": "1000*sum (rate (container_cpu_usage_seconds_total{container=~\"$container\"}[$interval]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(res_model_prediction_usage{container=~\"$container\",resource=\"cpu\", unit=\"m\"})",
     "legendFormat": "Predicted"
    },
    {
     "expr": "max(res_model_regression_coeff{coeff_name=\"offset\", container=~\"$container\", resource=\"cpu\"}) + max(res_model_regression_coeff{coeff_name=\"predictor_0\",container=~\"$container\",resource=\"cpu\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_0\",container=~\"$container\",resource=\"cpu\"}) + (max(res_model_regression_coeff{coeff_name=\"predictor_1\",container=~\"$container\",resource=\"cpu\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_1\",container=~\"$container\",resource=\"cpu\"}) OR vector(0)) + (max(res_model_regression_coeff{coeff_name=\"predictor_2\",container=~\"$container\",resource=\"cpu\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_2\",container=~\"$container\",resource=\"cpu\"}) OR vector(0))+ (max(res_model_regression_coeff{coeff_name=\"predictor_3\",container=~\"$container\",resource=\"cpu\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_3\",container=~\"$container\",resource=\"cpu\"}) OR vector(0))",
     "legendFormat": "Adhoc Prediction"
    }
   ]
  },
  {
   "title": "Mem $container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=~\"$container\"})/(1024*1024)",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(res_model_prediction_usage{container=~\"$container\",resource=\"mem\", unit=\"Mi\"})",
     "legendFormat": "Predicted"
    },
    {
     "expr": "max(res_model_regression_coeff{coeff_name=\"offset\", container=~\"$container\", resource=\"mem\"}) + max(res_model_regression_coeff{coeff_name=\"predictor_0\",container=~\"$container\",resource=\"mem\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_0\",container=~\"$container\",resource=\"mem\"}) + (max(res_model_regression_coeff{coeff_name=\"predictor_1\",container=~\"$container\",resource=\"mem\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_1\",container=~\"$container\",resource=\"mem\"}) OR vector(0)) + (max(res_model_regression_coeff{coeff_name=\"predictor_2\",container=~\"$container\",resource=\"mem\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_2\",container=~\"$container\",resource=\"mem\"}) OR vector(0))+ (max(res_model_regression_coeff{coeff_name=\"predictor_3\",container=~\"$container\",resource=\"mem\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_3\",container=~\"$container\",resource=\"mem\"}) OR vector(0))",
     "legendFormat": "Adhoc Prediction"
    }
   ]
  },
  { "title": "Predictors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Predictor CPU $container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "res_model_predictor_usage{container=~\"$container\",resource=\"cpu\"}",
     "legendFormat": "{{coeff_name}} : {{coeff_alias}}"
    }
   ]
  },
  {
   "title": "Predictor Mem $container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "res_model_predictor_usage{container=~\"$container\",resource=\"mem\"}",
     "legendFormat": "{{coeff_name}} : {{coeff_alias}}"
    }
   ]
  },
  { "title": "Correlation TO REMOVE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Control Sample Predictor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(res_control_measurement_pixels)",
     "legendFormat": "pixels"
    }
   ]
  },
  {
   "title": "Control Sample CPU best",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "m cores" } },
   "yaxes": [
    { "format": "m cores" }
   ],
   "targets": [
    {
     "expr": "1000*sum (rate (container_cpu_usage_seconds_total{container=\"resource-control-sample\"}[$interval]))",
     "legendFormat": "usage"
    },
    {
     "expr": "0.52 + 0.00000256 * sum(res_control_measurement_pixels)",
     "legendFormat": "Pred 1 pred 51% R²"
    },
    {
     "expr": "0.655 + 0.0000019 * sum(res_control_measurement_pixels) + 0.0098 * sum(go_goroutines{job=\"resource-control-sample\"})",
     "legendFormat": "Pred 2 pred 62% R²"
    },
    {
     "expr": "1.7 + 0.0000007 * sum(res_control_measurement_pixels)",
     "legendFormat": "Pred 1 pred 70% R²"
    }
   ]
  },
  {
   "title": "Control Sample Mem best",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=\"resource-control-sample\"})/(1024*1024)",
     "legendFormat": "usage"
    },
    {
     "expr": "8.52 + 0.000032* sum(res_control_measurement_pixels)",
     "legendFormat": "Predicted 91% R²"
    },
    {
     "expr": "37.8 + 0.000012* sum(res_control_measurement_pixels)",
     "legendFormat": "Predicted 99% R²"
    },
    {
     "expr": "12.08 + 0.00000867* sum(res_control_measurement_pixels)",
     "legendFormat": "Predicted 99.7% R²"
    }
   ]
  },
  {
   "title": "Control Sample Storage IOPS best",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_total{id=\"/\"}[$interval]) + on (device) group_right() container_fs_reads_total{container=\"resource-control-sample\"}*0",
     "legendFormat": "usage R"
    },
    {
     "expr": "irate(container_fs_writes_total{id=\"/\"}[$interval]) + on (device) group_right() container_fs_writes_total{container=\"resource-control-sample\"}*0",
     "legendFormat": "usage W"
    }
   ]
  },
  {
   "title": "Control Sample Storage Through best",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sdb\"}[$interval])",
     "legendFormat": "usage R"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sdb\"}[$interval])",
     "legendFormat": "usage W"
    }
   ]
  },
  {
   "title": "Control Sample Storage Usage best",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container=\"resource-control-sample\"})",
     "legendFormat": "usage cont"
    },
    {
     "expr": "sum(container_fs_usage_bytes{device=\"/dev/sdb\", id=\"/\"})",
     "legendFormat": "usage cont /"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device=\"/dev/sdb\",mountpoint=\"/\"}) - sum(node_filesystem_avail_bytes{device=\"/dev/sdb\",mountpoint=\"/\"})",
     "legendFormat": "usage node"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device=\"/dev/sdb\",mountpoint=\"/\"}) - sum(node_filesystem_avail_bytes{device=\"/dev/sdb\",mountpoint=\"/\"}) - 35500000000",
     "legendFormat": "usage node corect"
    }
   ]
  },
  {
   "title": "Control Sample Network Bandwidth best",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container=\"resource-control-sample\"}[$interval]))",
     "legendFormat": "usage received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container=\"resource-control-sample\"}[$interval]))",
     "legendFormat": "usage sent"
    }
   ]
  }
 ]
}