{
 "title": "Resource Model Exporter",
 "description": "To check the regression modeling of resources",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(res_model_regression_r2, container)"
    }
   },
   {
    "name": "resource",
    "query": {
     "query": "label_values(res_model_regression_r2, resource)"
    }
   },
   { "name": "interval", "query": "30s,1m,5m" }
  ]
 },
 "panels": [
  { "title": "Config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "res_model_config", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Sampling",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "res_model_config", "legendFormat": "{{interval}}" }
   ]
  },
  {
   "title": "max ROI",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "res_model_config", "legendFormat": "{{max_roi}}" }
   ]
  },
  {
   "title": "Node Type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "res_model_measurement_config{container=~\"$container\"}",
     "legendFormat": "{{node_type}}"
    }
   ]
  },
  {
   "title": "CPU model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "res_model_measurement_config{container=~\"$container\"}",
     "legendFormat": "{{cpu_model}}"
    }
   ]
  },
  {
   "title": "Docker Image Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "res_model_measurement_config{container=~\"$container\"}",
     "legendFormat": "{{image_version}}"
    }
   ]
  },
  { "title": "Regression Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  { "title": "$resource", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 4 }, "repeat": "resource" },
  {
   "title": "R²",
   "type": "stat",
   "description": "Quality of prediction (Best So Far)",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource,container)(res_model_regression_r2{resource=~\"$resource\",container=~\"$container\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Variance obs",
   "type": "stat",
   "description": "Range of the samples in the regression",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "repeat": "resource",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource,container)(res_model_regression_variance{resource=~\"$resource\",container=~\"$container\",variance_name=\"observed\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Variance pred",
   "type": "stat",
   "description": "Range of the samples in the regression",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "repeat": "resource",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource,container)(res_model_regression_variance{resource=~\"$resource\",container=~\"$container\",variance_name=\"predicted\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "N",
   "type": "stat",
   "description": "Number of samples in the regression",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 },
   "repeat": "resource",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource,container)(res_model_regression_n{resource=~\"$resource\",container=~\"$container\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "formula",
   "type": "stat",
   "description": "Formula",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 13 },
   "repeat": "resource",
   "targets": [
    {
     "expr": "res_model_regression_r2{resource=~\"$resource\",container=~\"$container\"}",
     "legendFormat": "{{formula}}"
    }
   ]
  },
  { "title": "Observed Usage vs Prediction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$resource",
   "type": "graph",
   "description": "To compare how the prediction is fitting the usage.\nPredicted is calculated by the resource exporter (based on BSF regression from the time being).\nBSF (Best So Far) Prediction is calculated using the BSF formula across past data.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (unit)(res_model_prediction_usage{container=~\"$container\",resource=~\"$resource\"})",
     "legendFormat": "Predicted  ({{unit}})"
    },
    {
     "expr": "max(res_model_regression_coeff{coeff_name=\"offset\", container=~\"$container\", resource=~\"$resource\"})\r\n + max(res_model_regression_coeff{coeff_name=\"predictor_0\",coeff_degree=\"1\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_0\",container=~\"$container\",resource=~\"$resource\"}) + (max(res_model_regression_coeff{coeff_name=\"predictor_1\",coeff_degree=\"1\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_1\",container=~\"$container\",resource=~\"$resource\"}) OR vector(0)) + (max(res_model_regression_coeff{coeff_name=\"predictor_2\",coeff_degree=\"1\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_2\",container=~\"$container\",resource=~\"$resource\"}) OR vector(0))+ (max(res_model_regression_coeff{coeff_name=\"predictor_3\",coeff_degree=\"1\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_3\",container=~\"$container\",resource=~\"$resource\"}) OR vector(0))\r\n  + max(res_model_regression_coeff{coeff_name=\"predictor_0\",coeff_degree=\"2\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_0\",container=~\"$container\",resource=~\"$resource\"})^2 + (max(res_model_regression_coeff{coeff_name=\"predictor_1\",coeff_degree=\"2\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_1\",container=~\"$container\",resource=~\"$resource\"})^2 OR vector(0)) + (max(res_model_regression_coeff{coeff_name=\"predictor_2\",coeff_degree=\"2\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_2\",container=~\"$container\",resource=~\"$resource\"})^2 OR vector(0))+ (max(res_model_regression_coeff{coeff_name=\"predictor_3\",coeff_degree=\"2\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_3\",container=~\"$container\",resource=~\"$resource\"})^2 OR vector(0))\r\n    + max(res_model_regression_coeff{coeff_name=\"predictor_0\",coeff_degree=\"3\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_0\",container=~\"$container\",resource=~\"$resource\"})^3 + (max(res_model_regression_coeff{coeff_name=\"predictor_1\",coeff_degree=\"3\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_1\",container=~\"$container\",resource=~\"$resource\"})^3 OR vector(0)) + (max(res_model_regression_coeff{coeff_name=\"predictor_2\",coeff_degree=\"3\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_2\",container=~\"$container\",resource=~\"$resource\"})^3 OR vector(0))+ (max(res_model_regression_coeff{coeff_name=\"predictor_3\",coeff_degree=\"3\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_3\",container=~\"$container\",resource=~\"$resource\"})^3 OR vector(0))\r\n    + max(res_model_regression_coeff{coeff_name=\"predictor_0\",coeff_degree=\"4\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_0\",container=~\"$container\",resource=~\"$resource\"})^4 + (max(res_model_regression_coeff{coeff_name=\"predictor_1\",coeff_degree=\"4\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_1\",container=~\"$container\",resource=~\"$resource\"})^4 OR vector(0)) + (max(res_model_regression_coeff{coeff_name=\"predictor_2\",coeff_degree=\"4\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_2\",container=~\"$container\",resource=~\"$resource\"})^4 OR vector(0))+ (max(res_model_regression_coeff{coeff_name=\"predictor_3\",coeff_degree=\"4\",container=~\"$container\",resource=~\"$resource\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_3\",container=~\"$container\",resource=~\"$resource\"})^4 OR vector(0))",
     "legendFormat": "BSF Prediction"
    },
    {
     "expr": "max by (unit)(res_model_observed_usage{container=~\"$container\",resource=~\"$resource\"})",
     "legendFormat": "Usage ({{unit}})"
    }
   ]
  },
  { "title": "Predictor Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Predictor $resource",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(coeff_name,coeff_alias)(res_model_predictor_usage{container=~\"$container\",resource=~\"$resource\"})",
     "legendFormat": "{{coeff_name}} : {{coeff_alias}}"
    }
   ]
  }
 ]
}