{
 "title": "Resource Model Exporter",
 "description": "To check the regression modeling of resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(res_model_regression_r2, container)"
    }
   },
   {
    "name": "resource",
    "query": {
     "query": "label_values(res_model_regression_r2, resource)"
    }
   },
   { "name": "interval", "query": "5m" }
  ]
 },
 "panels": [
  { "title": "Regression Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "R²",
   "type": "stat",
   "description": "Quality of prediction",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max by (resource,container)(res_model_regression_r2{resource=~\"$resource\",container=~\"$container\"})[$__range:])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Variance",
   "type": "stat",
   "description": "Range of the samples in the regression",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max by (resource,container)(res_model_regression_variance{resource=~\"$resource\",container=~\"$container\"})[$__range:])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "N",
   "type": "stat",
   "description": "Number of samples in the regression",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max by (resource,container)(res_model_regression_n{resource=~\"$resource\",container=~\"$container\"})[$__range:])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Reality vs Prediction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU $container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "m cores" } },
   "yaxes": [
    { "format": "m cores" }
   ],
   "targets": [
    {
     "expr": "1000*sum (rate (container_cpu_usage_seconds_total{container=~\"$container\"}[$interval]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(res_model_prediction_usage{container=~\"$container\",resource=\"cpu\", unit=\"m\"})",
     "legendFormat": "Predicted"
    }
   ]
  },
  {
   "title": "Mem $container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=~\"$container\"})/(1024*1024)",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(res_model_prediction_usage{container=~\"$container\",resource=\"mem\", unit=\"Mi\"})",
     "legendFormat": "Predicted"
    }
   ]
  },
  { "title": "Correlation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 251 } },
  {
   "title": "Node-exporter Mem",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 252 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=~\"$container\"})/(1024*1024)",
     "legendFormat": "usage"
    },
    {
     "expr": "20.5234 -0.0132 * scrape_samples_scraped{job=\"node-exporter\",instance=~\".*\"}",
     "legendFormat": "Predicted 98% R²"
    },
    {
     "expr": "max(res_model_regression_coeff{coeff_name=\"offset\", container=\"node-exporter\", resource=\"mem\"}) + max(res_model_regression_coeff{coeff_name=\"scraped_metrics\",container=\"node-exporter\",resource=\"mem\"}) * sum(scrape_samples_scraped{job=\"node-exporter\",instance=~\".*\"})",
     "legendFormat": "Predicted"
    }
   ]
  },
  {
   "title": "Node-exporter Predictor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 258 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped{job=\"node-exporter\",instance=~\".*\"})",
     "legendFormat": "scraped_metrics"
    }
   ]
  }
 ]
}