{
 "title": "Resource Model Exporter",
 "description": "To check the regression modeling of resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(res_model_regression_r2, container)"
    }
   },
   {
    "name": "resource",
    "query": {
     "query": "label_values(res_model_regression_r2, resource)"
    }
   },
   { "name": "interval", "query": "5m" }
  ]
 },
 "panels": [
  { "title": "Regression Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "R² $resource $container",
   "type": "stat",
   "description": "Quality of prediction",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "repeat": "resource",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max by (resource,container)(res_model_regression_r2{resource=~\"$resource\",container=~\"$container\"})[$__range:])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Variance $resource $container",
   "type": "stat",
   "description": "Range of the samples in the regression",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "repeat": "resource",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max by (resource,container)(res_model_regression_variance{resource=~\"$resource\",container=~\"$container\"})[$__range:])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "N $resource $container",
   "type": "stat",
   "description": "Number of samples in the regression",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "repeat": "resource",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max by (resource,container)(res_model_regression_n{resource=~\"$resource\",container=~\"$container\"})[$__range:])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "formula $resource $container",
   "type": "stat",
   "description": "Number of samples in the regression",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "repeat": "resource",
   "targets": [
    {
     "expr": "res_model_regression_r2{resource=~\"$resource\",container=~\"$container\"}",
     "legendFormat": "{{formula}}"
    }
   ]
  },
  { "title": "Real Usage vs Prediction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU $container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "m cores" } },
   "yaxes": [
    { "format": "m cores" }
   ],
   "targets": [
    {
     "expr": "1000*sum (rate (container_cpu_usage_seconds_total{container=~\"$container\"}[$interval]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(res_model_prediction_usage{container=~\"$container\",resource=\"cpu\", unit=\"m\"})",
     "legendFormat": "Predicted"
    },
    {
     "expr": "max(res_model_regression_coeff{coeff_name=\"offset\", container=~\"$container\", resource=\"cpu\"}) + max(res_model_regression_coeff{coeff_name=\"predictor_0\",container=~\"$container\",resource=\"cpu\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_0\",container=~\"$container\",resource=\"cpu\"}) + (max(res_model_regression_coeff{coeff_name=\"predictor_1\",container=~\"$container\",resource=\"cpu\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_1\",container=~\"$container\",resource=\"cpu\"}) OR vector(0)) + (max(res_model_regression_coeff{coeff_name=\"predictor_2\",container=~\"$container\",resource=\"cpu\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_2\",container=~\"$container\",resource=\"cpu\"}) OR vector(0))+ (max(res_model_regression_coeff{coeff_name=\"predictor_3\",container=~\"$container\",resource=\"cpu\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_3\",container=~\"$container\",resource=\"cpu\"}) OR vector(0))",
     "legendFormat": "Adhoc Prediction"
    }
   ]
  },
  {
   "title": "Mem $container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=~\"$container\"})/(1024*1024)",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(res_model_prediction_usage{container=~\"$container\",resource=\"mem\", unit=\"Mi\"})",
     "legendFormat": "Predicted"
    },
    {
     "expr": "max(res_model_regression_coeff{coeff_name=\"offset\", container=~\"$container\", resource=\"mem\"}) + max(res_model_regression_coeff{coeff_name=\"predictor_0\",container=~\"$container\",resource=\"mem\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_0\",container=~\"$container\",resource=\"mem\"}) + (max(res_model_regression_coeff{coeff_name=\"predictor_1\",container=~\"$container\",resource=\"mem\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_1\",container=~\"$container\",resource=\"mem\"}) OR vector(0)) + (max(res_model_regression_coeff{coeff_name=\"predictor_2\",container=~\"$container\",resource=\"mem\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_2\",container=~\"$container\",resource=\"mem\"}) OR vector(0))+ (max(res_model_regression_coeff{coeff_name=\"predictor_3\",container=~\"$container\",resource=\"mem\"}) * max(res_model_predictor_usage{coeff_name=\"predictor_3\",container=~\"$container\",resource=\"mem\"}) OR vector(0))",
     "legendFormat": "Adhoc Prediction"
    }
   ]
  },
  { "title": "Predictors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Predictor CPU $container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "res_model_predictor_usage{container=~\"$container\",resource=\"cpu\"}",
     "legendFormat": "{{coeff_name}} : {{coeff_alias}}"
    }
   ]
  },
  {
   "title": "Predictor Mem $container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "res_model_predictor_usage{container=~\"$container\",resource=\"mem\"}",
     "legendFormat": "{{coeff_name}} : {{coeff_alias}}"
    }
   ]
  },
  { "title": "Correlation TO REMOVE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Node-exporter Mem",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=~\"$container\"})/(1024*1024)",
     "legendFormat": "usage"
    },
    {
     "expr": "20.5234 -0.0132 * scrape_samples_scraped{job=\"node-exporter\",instance=~\".*\"}",
     "legendFormat": "Predicted 98% R²"
    },
    {
     "expr": "max(res_model_regression_coeff{coeff_name=\"offset\", container=\"node-exporter\", resource=\"mem\"}) + max(res_model_regression_coeff{coeff_name=\"scraped_metrics\",container=\"node-exporter\",resource=\"mem\"}) * sum(scrape_samples_scraped{job=\"node-exporter\",instance=~\".*\"})",
     "legendFormat": "Predicted"
    }
   ]
  },
  {
   "title": "Node-exporter Predictor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped{job=\"node-exporter\",instance=~\".*\"})",
     "legendFormat": "scraped_metrics"
    }
   ]
  }
 ]
}